#!/usr/bin/python3
# This code write by Mr.nope
import os
import time
import platform
import sys
system = platform.uname()[0]
SM_Finish_Installing = "\nInstalling..., Finish...!\n"
def cls():
    os.system("clear")
if system == 'Linux':
  os.system("chmod a+x SM.py")
  os.system("sudo cp SM.py /usr/local/bin")
  os.system("sudo cp SM.py /usr/lib/python3.6")
  time.sleep(1)
  print(SM_Finish_Installing)
  sys.exit()
elif system == 'Windows':
    print("\nPlease, run This Programm on Linux or MacOS!\n")
    sys.exit()
elif system == 'Mac':
    os.system("chmod a+x SM.py")
    os.system("sudo cp SM.py /usr/local/bin")
    os.system("sudo cp SM.py /usr/lib/python3.6")
    time.sleep(1)
    print(SM_Finish_Installing)
    sys.exit()
# This code write on Linux,Windows,MacOs
else:
    print("This programm run as: Linux,MacOs!")
    try_to_exit = input("press Enter...")
    if try_to_exit == '':
      cls()
      sys.exit()
    else:
        cls()
        sys.exit()
