#!/usr/bin/bash
# This code write by Mr.nope
clear
echo "Uninstalling..."
sleep 2
cd /usr/lib/python3.6 && sudo rm SM.pyc
cd /usr/local/bin && sudo rm SM.pyc
echo ""
echo "Uninstalling..., Finish...!"
echo ""
exit 1
